pipeline{
    agent any


    environment{
        DOCKERHUB_USERNAME= "wissem007"
        APP_NAME = "gitops-argocd_CI"
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGES_NAME = "${DOCKERHUB_USERNAME}" + "/" + "${DOCKERHUB_USERNAME}"
        REGISTRY_CREDS ='dockerhub'
    }
        
    
    stages{
        stage("clenup workspace"){
            steps{
                script {
                    // sh "rm -rf *"
                    cleanWs()

                }
               
            }
             
        }
    }
 
}