pipeline{
    agent any


    environment{
        DOCKERHUB_USERNAME= "wissem007"
        APP_NAME = "gitops-argocd_CI"
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGES_NAME = "${DOCKERHUB_USERNAME}" + "/" + "${DOCKERHUB_USERNAME}"
        REGISTRY_CREDS ='dockerHub'
    }
        
    
    stages{
        stage("clenup workspace"){
            steps{
                script {
                    // sh "rm -rf *"
                    cleanWs()

                }
               
            }
             
        }
        stage("checkout  SCM"){
                    steps{
                        script {
                            git credentialsId: 'github',
                            url: 'https://github.com/wissem007/gitops-argocd_CI.git',
                            branch: 'master'

                        }
                    
                    }
                    
                }
         stage("Docker build Image"){
                    steps{
                        script {
                            docker_image = docker.build "${IMAGES_NAME}"
         

                        }
                    
                    }
                    
                }




    }
 
}