pipeline{
    agent any
        
    
    stages{
        stage("clenup workspace"){
            steps{
                script {
                    // sh "rm -rf *"
                    cleanWs()

                }
               
            }
             
        }
    }
 
}